//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEPTIONLOG
    {
        public long ID { get; set; }
        public string EXCEPTION_MESSAGE { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public string STACKTRACE { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
        public string USERNAME { get; set; }
    }
}
