//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_OSP_CABLE_STRUCT
    {
        public long STRUCT_ID { get; set; }
        public string STRUCT_NAME { get; set; }
        public string STRUCT_OT_NAME { get; set; }
        public long CABLE_ID { get; set; }
        public string CABLE_NAME { get; set; }
        public string CABLE_OT_NAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
