//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_NE_ABE
    {
        public long ABE_ID { get; set; }
        public string ABE_NAME { get; set; }
        public long ABE_OT_ID { get; set; }
        public string ABE_OT_NAME { get; set; }
        public string NE_NAME { get; set; }
        public long NE_ID { get; set; }
        public long NE_OT_ID { get; set; }
        public string NE_OT_NAME { get; set; }
    
        public virtual ONNET_SRCH_NE ONNET_SRCH_NE { get; set; }
    }
}
