//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_OSP_CABLE
    {
        public string CABLE_ID { get; set; }
        public string NAME { get; set; }
        public string OBJECT_TYPE_ID { get; set; }
        public string NUM_OF_FIBERS { get; set; }
        public string Cable_Type { get; set; }
        public string LENGTH { get; set; }
        public string ADM_STATUS { get; set; }
        public string MANUFACTURER { get; set; }
        public string COLOR_SCHEMA { get; set; }
        public string GEODATA { get; set; }
    }
}
