//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_BUILDING
    {
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public string STREET_ID { get; set; }
        public string BUILDING { get; set; }
        public string BUILDING_ID { get; set; }
        public string GEODATA { get; set; }
        public string AREA { get; set; }
        public string CLUST { get; set; }
        public string Post_Code { get; set; }
        public string Block_Name { get; set; }
        public string Number { get; set; }
        public string APARTMENTS { get; set; }
    }
}
