//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_OSP_THRESHOLD
    {
        public string NE_ID { get; set; }
        public string NE_NAME { get; set; }
        public string NE_OT_ID { get; set; }
        public string DEV_ID { get; set; }
        public string DEV_NAME { get; set; }
        public string DEV_OT_ID { get; set; }
        public string THR_TEMPL_ID { get; set; }
        public string TRH_TEMPL_NAME { get; set; }
        public string TOTAL { get; set; }
        public string AVAIL { get; set; }
        public string USED { get; set; }
        public string VALUE { get; set; }
        public string OLD_VALUE { get; set; }
        public string PLANNED_TO_USE { get; set; }
        public string IS_DEV { get; set; }
        public string F16 { get; set; }
    }
}
