//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_OSP_CABLE
    {
        public long CABLE_ID { get; set; }
        public string CABLE_NAME { get; set; }
        public long CABLE_OT_ID { get; set; }
        public string CABLE_OT_NAME { get; set; }
        public Nullable<int> NUM_OF_FIBERS { get; set; }
        public string CABLE_TYPE { get; set; }
        public string LENGTH { get; set; }
        public string ADM_STATUS { get; set; }
        public string MANUFACTURER { get; set; }
        public string COLOR_SCHEMA { get; set; }
        public System.Data.Entity.Spatial.DbGeography GEODATA { get; set; }
        public Nullable<System.DateTime> LTST_CRTD_WHEN { get; set; }
        public Nullable<System.DateTime> LTST_UPTD_WHEN { get; set; }
    }
}
