//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_OSP_THRESHOLD
    {
        public long NE_ID { get; set; }
        public string NE_NAME { get; set; }
        public Nullable<long> NE_OT_ID { get; set; }
        public string NE_OT_NAME { get; set; }
        public long DEV_ID { get; set; }
        public string DEV_NAME { get; set; }
        public Nullable<long> DEV_OT_ID { get; set; }
        public long THR_TEMPL_ID { get; set; }
        public string TRH_TEMPL_NAME { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> AVAIL { get; set; }
        public Nullable<decimal> USED { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public Nullable<decimal> OLD_VALUE { get; set; }
        public Nullable<decimal> PLANNED_TO_USE { get; set; }
        public Nullable<decimal> IS_DEV { get; set; }
    }
}
