//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONNET_SRCH_DL_ID_LIST
    {
        public long NE_ID { get; set; }
        public Nullable<long> DL_ID { get; set; }
        public string DL_NAME { get; set; }
        public long DL_OT_ID { get; set; }
        public string DL_OT_NAME { get; set; }
        public long OBJECT_ID { get; set; }
    
        public virtual ONNET_SRCH_NE ONNET_SRCH_NE { get; set; }
    }
}
